#
# SPDX-FileCopyrightText: 2024 Georg Kunz <der.schorsch@gmail.com>
# SPDX-License-Identifier: MIT
#
name: Run unit tests

on:
  pull_request: null

permissions: read-all

jobs:
  tests:
    permissions:
      contents: read
      packages: read
      statuses: write

    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Set up Python
      uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: python3 -m pip install .
    - name: Run unit tests
      run: |
        pushd tests
        python3 unit_tests.py
