name: Run unit tests

on:
  pull_request: null

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"
    - name: Install pypa/build
      run: >-
        pushd tests
        python3 unit_tests.py
